---
- hosts: localhost
  become: true
  tasks:
    - name: Install Kubectl using Snap
      snap:
        name: kubectl
        classic: true

    - name: Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    - name: Start Minikube
      shell: |
        minikube start --driver=none

    - name: Deploy application to Kubernetes
      shell: |
        kubectl apply -f deployment.yml
        kubectl rollout status deployment/cw2-server

    - name: Verify Deployment
      shell: |
        kubectl get pods

    - name: Install conntrack
      apt:
      name: conntrack
      state: present
